version: '3'

services:
  reconaug:
    build: .
    container_name: reconaug
    ports:
      - "5001:5001"
    volumes:
      - ./output:/app/output
      - ./instance:/app/instance
    restart: unless-stopped
